Sprint 7 solution in file manager
IlyaKot98/java-kanban pull request #2
Opened 2024-04-18 20:43 UTC by IlyaKot98

Был реализован функционал записи истории в файл.
Создан класс FileBackedTaskManager, реализующий функционал обработки задачи и запись/чтение ее в файл формата ".csv".

2024-04-20 08:59 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-04-20 08:59 UTC, ErkinKasymaliev commented on src/manager/FileBackedTaskManager.java
> +    public String toString(Task task) {
этот метод и 3 ниже уберите в какой-нибудь утилитарный класс, например, FormatterUtil и сделай их статиками

2024-04-20 08:59 UTC, ErkinKasymaliev commented on src/Main.java
> +        File file = new File( "test.csv");
1) Заведите несколько разных задач, эпиков и подзадач. То есть сохраните их в файл
2) Создайте новый FileBackedTaskManager-менеджер из этого же файла. Прочитай файл
3) Проверьте, что все задачи, эпики, подзадачи, которые были в старом менеджере, есть в новом.  То есть проверьте через метод equals() что таски, сабтаски, эпики и истории равны

2024-04-22 14:23 UTC, ErkinKasymaliev reviewed
привет, оставил комменты

2024-04-22 14:23 UTC, ErkinKasymaliev commented on src/Main.java
> +        System.out.println("История равна: " + strOld.equals(srtNew));
так не пойдет, не надо переводить в стринги и сравнивать -- это очень очень плохо, за такое могут унизить на код-ревью)
сделайте следующее: реализуйте методы equals() и hashCode() для Task, Subtask, Epic (эти методы вы должны уже знать) и у вас будет следующее:
System.out.println("История равна: " + managerOrig.getHistory().equals(managerNew.getHistory()));
getHistory - вернут коллекцию String, equals для String уже реализован из под коробки jdk.
  System.out.println("Задачи равны: " + managerOrig.getTasks().equals(managerNew.getTasks));
и так далее

2024-04-22 20:01 UTC, IlyaKot98 commented on src/Main.java
> +        System.out.println("История равна: " + strOld.equals(srtNew));
Спасибо за совет) все исправил

2024-04-23 13:53 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2024-05-13 22:44 UTC, merged