feat: Добавил дату старта и продолжительность задач. Добавил метод ра…
IlyaKot98/java-kanban pull request #3
Opened 2024-05-27 22:04 UTC by IlyaKot98

…счета времени завершения задачи. Подредактирован файловый менеджер, чтобы имел возможность записывать всю информацию о задачи в файл, и брать из него.

2024-05-28 05:57 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-05-28 05:57 UTC, ErkinKasymaliev commented on src/manager/createException.java
> +public class createException extends Throwable{
С большой буквы название классов

2024-05-28 05:57 UTC, ErkinKasymaliev commented on src/manager/InMemoryTaskManager.java
> +       for (Integer i : epic.getSubtaskId()) {
через stream api давайте
```
Set<LocalDateTime> subtaskStartTime = epic.getSubtasId().stream()
    .map(Subtask::getStartTime)
    .collect(Collector.toSet());
```

2024-05-28 10:27 UTC, IlyaKot98 commented
Исправил)

2024-05-29 06:45 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2024-06-02 19:02 UTC, merged