Sprint 9 solution http api
IlyaKot98/java-kanban pull request #4
Opened 2024-07-04 13:18 UTC by IlyaKot98

feat: Добавлена обработка запросов и тесты для GET/POST/DELETE /tasks , GET/POST/DELETE /subtasks , GET/POST/DELETE /epics , GET /history , GET /prioritized

2024-07-05 08:08 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-07-05 08:08 UTC, ErkinKasymaliev commented on src/manager/CreateException.java
> +
давайте уберем в отдельный пакет exceptions

2024-07-05 08:08 UTC, ErkinKasymaliev commented on src/manager/JsonManager.java
> +public class JsonManager {
JsonUtil

2024-07-05 08:08 UTC, ErkinKasymaliev commented on src/manager/JsonManager.java
> +public class JsonManager {
и что то не увидел где вы его используете. удалите

2024-07-05 08:08 UTC, ErkinKasymaliev commented on src/handlers/HttpTaskServer.java
> +    FileBackedTaskManager manager;
модификатор доступа

2024-07-05 08:08 UTC, ErkinKasymaliev commented on src/handlers/HttpTaskServer.java
> +    HttpServer httpServer = HttpServer.create();
модификатор доступа

2024-07-05 08:08 UTC, ErkinKasymaliev commented on src/handlers/TaskHandler.java
> +    Gson gson = new GsonBuilder()
модификатор доступа

2024-07-05 10:37 UTC, IlyaKot98 commented on src/handlers/HttpTaskServer.java
> +    FileBackedTaskManager manager;
done

2024-07-05 10:37 UTC, IlyaKot98 commented on src/handlers/HttpTaskServer.java
> +    HttpServer httpServer = HttpServer.create();
done

2024-07-05 10:38 UTC, IlyaKot98 commented on src/handlers/TaskHandler.java
> +    Gson gson = new GsonBuilder()
done

2024-07-05 10:39 UTC, IlyaKot98 commented on src/manager/JsonManager.java
> +public class JsonManager {
done

2024-07-06 07:50 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2024-07-06 22:57 UTC, merged